# Configuration file for StatusPlugin
# Version to compare
current_version: "4.8"

#  ##########################################
#  ||                                      ||
#  ||       Status Plugin by Markap        ||
#  ||                                      ||
#  ##########################################


# Configuration file for StatusPlugin

# Command name to set the status
command-name: status

# Default status configuration
default_status_enabled: false
default_status: "&8[&7Player&8]&r" #--> [Player]

# Format for chat messages
chat-format: "%status% &r<$$PLAYER$$> "
chat-format-no-status: "<$$PLAYER$$> "

# Format for the player list (tab list)
tab-list-format: "&a%status% &r $$PLAYER$$"

# Allow only admins to change the status
only-admin-change: false
# Message to display when only admins can change statuses
only-admin-change-message: "&cOnly admins can change statuses."


# Enable or disable tab styling
tab-styling-enabled: true

# Enable or disable chat styling
chat-styling-enabled: true

# Available status options
# You can add more status options in the status-options.yml

# Enable or disable the admin join info message
admin-join-message-enabled: false

# Language configuration
language:
  use_only_one: true #please leave this on "true" for now
  default_language: "main" # please leave this on "main" for now

# i --> when you want to change the messages, go to the language.yml !

